---
title: "PS5"
author: "Simran Bhatti"
date: "2023-02-18"
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)

```

# Loading and checking data

```{r, message=False}
gapminder <- read.delim("C:/Users/simra/Documents/Simran Bhatti/INFO 201/ps5-simmi33/gapminder.csv.bz2")

gapminder
```

### Amount of rows and columns:

```{r, message=FALSE}

rows <- nrow(gapminder)
cat("\nThe amount of rows are:", rows)
```

**There are 13,055 rows**

```{r, message=FALSE}
columns <- ncol(gapminder)
cat("\nThe amount of columns are:", columns)
```

**There are 25 columns**

```{r, message=FALSE}
tails <- tail(gapminder)
cat("\nHere are a few lines of data:\n")
print(tails)
```

### Descriptive statistics

```{r}
gapminder %>%
  distinct(gapminder$name) %>%
  count()
```

*There are 250 countries under 'name'*

```{r}
gapminder %>%
  distinct(gapminder$iso2) %>%
  count()
```

*There are 249 countries under 'iso2'*

```{r}
gapminder %>%
distinct(gapminder$iso3) %>%
  count()
```

*There are 253 countries under 'iso3'*
